### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [pyloa/PyLoa#8]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyloa -w /tmp/ext pyloa==1.0.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyloa==1.0.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/f08/8d040456d2ab7/pyloa-1.0.3.tar.gz (46 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-smeumpfp/pyloa/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-smeumpfp/pyloa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-smeumpfp/pyloa/pip-egg-info
         cwd: /tmp/pip-wheel-smeumpfp/pyloa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-smeumpfp/pyloa/setup.py", line 20, in <module>
        with open(requirements_file, encoding='utf-8', mode='r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-smeumpfp/pyloa/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
There's a dep on a version of tensorflow that doesn't exist so I can't autofix.

**Comment by SebastianSchoenitz** [comment]
Thanks @thatch for filing the issue.
The problem probably lies in your python version. I guess you use python 3.8.
With 3.8 I was able to reproduce the error. The problem is, that tensorflow doesn't support python 3.8 or vice visa. So, I will rather port PyLoa to TF 2.x, but I have a fix for you in the meantime.
Based on https://stackoverflow.com/a/61430652 you could try the following:

`
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7 python3.7-venv python3.7-tk
python3.7 -m venv venv37
source venv37/bin/activate
pip install pyloa
`
Please report if this solves your issue.

**Comment by SebastianSchoenitz** [comment]
Okay, I think this issue can be closed.
